# -*- coding: utf-8 -*-
"""loss_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFiOyoLO_bFeLC8bvUWtbI1Fja3Rz1Wk
"""

# Tạo hàm kiểm tra n có phải là số nguyên không
def check_interger(n):
  n = input(f'Nhập số lượng samples ')
  if n.isnumeric():
    pass
  else:
    print('n phải là một số nguyên')
check_interger(n) # Gọi hàm kiểm tra n
# Tạo hàm để nhập loại loss function
loss_name = input(f'Nhập loại loss function ')
# Tạo vòng lặp
import random
for i in range (n):
  target = random.uniform(0.0,10.0)
  predict = random.uniform(0.0,10.0)
  print(f'target: {target}, predict: {predict}')
  mae = (abs(target-predict))/n
  mse = ((target-predict)**2)/n
  # Phân loại loss function
  if loss_name == 'mae':
    print(f'mae: {mae}')
  elif loss_name == 'mse':
    print(f'mse: {mse}')
  else:
    print('Nhập sai')

import math
def calc_ae(y, y_hat):
  ae = math.fabs(y-y_hat)
  return ae

assert calc_ae(10, 6)==5

y=2
y_hat = 9
print(calc_ae(y,y_hat))

import math
def calc_se(y, y_hat):
  se = (y-y_hat)**2
  return se
y = 4
y_hat = 2
assert calc_se(y, y_hat)==4
print(calc_se(2,1))

