# -*- coding: utf-8 -*-
"""md_nre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmX2uGY2e3kWmGXv5E8Wh0XW9VC342LY
"""

import math
def md_nre(y,y_hat,n,p):
  return ((y**(1/n))-(y_hat**(1/n)))**p
print(md_nre(100,99.5,2,1))

print(md_nre(50,49.5,2,1))

