# -*- coding: utf-8 -*-
"""sin_cos_sinh_cosh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfNWD-mbV23mkdGgNxxVyhSn4Iz4sOtQ
"""

import math
def approx_cos(x,n):
    result = 0
    for i in range(n):
        term = (((-1)**i)*(x**(2*i)))/ math.factorial(2*i)
        result = result + term
    return result
assert round(approx_cos(x=1,n=10),2) == 0.54
print(round(approx_cos(x=3.14,n=10),2))

def approx_sin(x,n):
    result = 0
    for i in range(n):
        term = (((-1)**i)*(x**(2*i+1)))/ math.factorial(2*i+1)
        result = result + term
    return result
assert round(approx_sin(x=1,n=10),4) == 0.8415
print(round(approx_sin(x=3.14,n=10),4))

def approx_sinh(x,n):
  result = 0
  for i in range(n):
    term = x**(2*i+1)/math.factorial(2*i+1)
    result = result + term
  return result
assert round(approx_sinh(x=1,n=10),2) == 1.18
print(round(approx_sinh(x=3.14,n=10),2))

def approx_cosh(x,n):
  result = 0
  for i in range(n):
    term = x**(2*i)/math.factorial(2*i)
    result = result + term
  return result
assert round(approx_cosh(x=1,n=10),2) == 1.54
print(round(approx_cosh(x=3.14,n=10),2))

